import type { Activity } from '../types/activity'

const now = new Date().toISOString()
const daysAgo = (n: number) =>
  new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString()

export const DEMO_ACTIVITIES: Activity[] = [
  {
    id: 'demo-1',
    title: 'Sunrise at Mount Tam',
    notes: 'Pack coffee and a blanket',
    location: 'Mill Valley, CA',
    estimated_cost: '$0',
    tag: 'outdoors',
    category: 'north_cali',
    completed: false,
    favorite: true,
    created_at: daysAgo(14),
    completed_at: null,
    updated_at: daysAgo(14),
  },
  {
    id: 'demo-2',
    title: 'Tartine Manufactory brunch',
    notes: 'Get the morning bun',
    location: 'San Francisco, CA',
    estimated_cost: '$40',
    tag: 'food',
    category: 'north_cali',
    completed: true,
    favorite: false,
    created_at: daysAgo(30),
    completed_at: daysAgo(3),
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-3',
    title: 'Big Sur coastal drive',
    notes: 'Stop at Bixby Bridge',
    location: 'Highway 1',
    estimated_cost: '$60 gas',
    tag: 'travel',
    category: 'north_cali',
    completed: false,
    favorite: true,
    created_at: daysAgo(7),
    completed_at: null,
    updated_at: daysAgo(7),
  },
  {
    id: 'demo-4',
    title: 'Griffith Observatory at dusk',
    notes: 'City lights view',
    location: 'Los Angeles, CA',
    estimated_cost: '$0',
    tag: 'date_night',
    category: 'south_cali',
    completed: false,
    favorite: true,
    created_at: daysAgo(10),
    completed_at: null,
    updated_at: daysAgo(10),
  },
  {
    id: 'demo-5',
    title: 'Joshua Tree camping weekend',
    notes: 'Bring warm layers at night',
    location: 'Joshua Tree, CA',
    estimated_cost: '$120',
    tag: 'adventure',
    category: 'south_cali',
    completed: false,
    favorite: true,
    created_at: daysAgo(5),
    completed_at: null,
    updated_at: daysAgo(5),
  },
  {
    id: 'demo-6',
    title: 'Grand Central Market food crawl',
    notes: "Try Eggslut and Sarita's",
    location: 'Downtown LA',
    estimated_cost: '$50',
    tag: 'food',
    category: 'south_cali',
    completed: true,
    favorite: false,
    created_at: daysAgo(20),
    completed_at: daysAgo(7),
    updated_at: daysAgo(7),
  },
  {
    id: 'demo-7',
    title: 'Stargazing picnic',
    notes: 'Download a constellation app',
    location: 'Anywhere dark',
    estimated_cost: '$15',
    tag: 'date_night',
    category: 'either',
    completed: false,
    favorite: true,
    created_at: daysAgo(3),
    completed_at: null,
    updated_at: daysAgo(3),
  },
  {
    id: 'demo-8',
    title: 'Cook a new recipe together',
    notes: "Pick something from a cookbook we haven't tried",
    location: 'Home',
    estimated_cost: '$25',
    tag: 'food',
    category: 'either',
    completed: false,
    favorite: false,
    created_at: now,
    completed_at: null,
    updated_at: now,
  },
  {
    id: 'demo-9',
    title: 'Board game café night',
    notes: 'Try something cooperative',
    location: 'Local café',
    estimated_cost: '$30',
    tag: 'coffee',
    category: 'either',
    completed: true,
    favorite: false,
    created_at: daysAgo(12),
    completed_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
]
